name = "my-pages-app"
pages_build_output_dir = "./dist"

# Bind an R2 Bucket. Use R2 to store arbitrarily large blobs of data, such as files.
# Docs: https://developers.cloudflare.com/pages/functions/bindings/#r2-buckets
[[r2_buckets]]
binding = "POKEDEX"
bucket_name = "pokedex"

[dev]
# Dev server settings. Using a fixed port here so that we can reliably set vite to proxy API requests to the wrangler
port = 8787

[env.production]
r2_buckets = [
	{ binding = "POKEDEX", bucket_name = "pokedex-DEV" }
]

[env.preview]
r2_buckets = [
	{ binding = "POKEDEX", bucket_name = "pokedex-DEV" }
]

[vars]
# Variables made available to API functions (but not the FE)
# https://developers.cloudflare.com/workers/configuration/environment-variables/

# To configure variables for the FE, use `.env.`
# https://vitejs.dev/guide/env-and-mode

# This should not be used for secrets (values you don't want in source control). For secrets, use `.dev.vars`
# https://developers.cloudflare.com/workers/configuration/secrets/

APP_MODE = 'development'
APP_NAME = 'CSR dev'



[env.preview.vars]
APP_NAME = 'CSR preview'
APP_MODE = 'preview'


[env.production.vars]
APP_MODE = 'production'
APP_NAME = 'CSR production'



